# Generated by Django 3.0.6 on 2020-06-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(default='this is cool!'),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(default='Job Title', max_length=120),
        ),
    ]
