# Generated by Django 3.0.6 on 2020-06-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200618_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(default='this is cool!')),
                ('position', models.CharField(default='Job Title', max_length=120)),
            ],
        ),
    ]
