# Generated by Django 3.0.6 on 2020-06-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200618_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
