# Generated by Django 3.0.6 on 2020-06-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200618_0425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
