# Generated by Django 3.0.6 on 2020-06-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200622_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
