# Generated by Django 3.0.6 on 2020-06-29 18:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200624_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, default='person/avatars/default.png', null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
