# Generated by Django 3.0.6 on 2020-07-14 22:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200714_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='604-123-4567', max_length=128, region=None),
        ),
    ]
