# Generated by Django 3.0.6 on 2020-07-25 03:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200714_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+12125552368', max_length=128, region=None),
        ),
    ]
