# Generated by Django 3.0.6 on 2020-07-08 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='type',
            new_name='sensor_type',
        ),
    ]
