# Generated by Django 3.0.6 on 2020-07-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_type',
        ),
    ]
