# Generated by Django 3.0.6 on 2020-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20200710_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='values',
            new_name='value',
        ),
        migrations.AddField(
            model_name='sensor',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='threshold_max',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='threshold_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
