# Generated by Django 3.0.6 on 2020-07-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_merge_20200703_1654'),
        ('sensor', '0003_sensor_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='slug',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('voc', 'Volatile Organic Compound'), ('co2', 'Carbon Dioxide')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='organization.Organization'),
        ),
    ]
