# Generated by Django 3.0.6 on 2020-07-26 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_auto_20200722_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
