# Generated by Django 3.0.6 on 2020-07-09 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_auto_20200708_1527'),
        ('sensor', '0004_auto_20200708_1759'),
    ]

    operations = [
    ]
