# Generated by Django 3.0.6 on 2020-07-26 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_sensor_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
