# Generated by Django 3.0.6 on 2020-06-26 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization',
            new_name='name',
        ),
        migrations.AddField(
            model_name='organization',
            name='color',
            field=models.CharField(default='#1B9A4B', max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='undefined', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
