# Generated by Django 3.0.6 on 2020-07-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20200701_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
