# Generated by Django 3.0.7 on 2020-07-02 01:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20200701_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
