# Generated by Django 3.0.7 on 2020-07-02 02:07

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20200701_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='color',
            field=colorful.fields.RGBColorField(),
        ),
    ]
