# Generated by Django 3.0.6 on 2020-07-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20200701_1929'),
        ('organization', '0006_auto_20200701_2041'),
    ]

    operations = [
    ]
