# Generated by Django 3.0.6 on 2020-07-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_merge_20200701_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='None', max_length=12, null=True),
        ),
    ]
