# Generated by Django 3.0.6 on 2020-07-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20200701_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='color',
        ),
    ]
