# Generated by Django 3.0.6 on 2020-07-02 04:40

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_remove_organization_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='color',
            field=colorful.fields.RGBColorField(default='#1B9A4B'),
        ),
    ]
