# Generated by Django 3.0.6 on 2020-07-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_organization_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
