# Generated by Django 3.0.6 on 2020-07-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20200701_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
