# Generated by Django 3.0.7 on 2020-07-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20200701_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
