# Generated by Django 3.0.6 on 2020-07-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20200702_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='avatar',
            field=models.ImageField(blank=True, default="{% static 'img/placeholder.jpg' %}", null=True, upload_to=''),
        ),
    ]
