# Generated by Django 3.0.7 on 2020-07-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20200702_1913'),
        ('organization', '0016_organization_picture'),
    ]

    operations = [
    ]
