# Generated by Django 3.0.6 on 2020-07-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_auto_20200702_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
