# Generated by Django 3.0.6 on 2020-07-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_auto_20200702_2138'),
        ('organization', '0020_auto_20200702_2143'),
    ]

    operations = [
    ]
