# Generated by Django 3.0.7 on 2020-07-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_auto_20200702_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
