# Generated by Django 3.0.7 on 2020-07-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_auto_20200702_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_avatar',
            field=models.ImageField(null=True, upload_to='org'),
        ),
    ]
