# Generated by Django 3.0.6 on 2020-07-03 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_auto_20200703_1145'),
        ('organization', '0022_remove_organization_avatar'),
    ]

    operations = [
    ]
