# Generated by Django 3.0.6 on 2020-07-26 22:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0040_auto_20200725_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='604-123-4567', max_length=128, null=True, region=None),
        ),
    ]
