# Generated by Django 3.0.6 on 2020-07-28 19:07

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0042_auto_20200727_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='color',
            field=colorful.fields.RGBColorField(default='#000000'),
        ),
    ]
