# Generated by Django 3.0.6 on 2020-07-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0043_auto_20200728_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
